### ISSUE TITLE
How to apply it to the data files ?

### ISSUE THREAD

**Issue by mateo-vial** [rflamary/OST#2]
When running demo_unmix.py, it seems to work in real time with my voice through the microphone. 
How do I try it with NIPS.wav and smile.wav ?

**Comment by rflamary** [comment]
Hello @mateo-vial  I usually play the wave file on my computer.

On linux you can change the audio setting/mixer so that the microphone for the python app is the system audio (and get no noise) or just use the microphone that will have some noise but is usually robust.

**Comment by mateo-vial** [comment]
Alright, I thought there was a way to directly plug the files in the program. I will find a way to do the same as you described for Linux on Windows
Thanks!
